// <auto-generated />
namespace FProyectBD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kesç : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kesç));
        
        string IMigrationMetadata.Id
        {
            get { return "201511280303241_kesç"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
